// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBslETljLKindUxA24f4Rln3klXpV49R5Q',
    appId: '1:549681889329:web:debbf048a18181f2e75510',
    messagingSenderId: '549681889329',
    projectId: 'authoryourbrand',
    authDomain: 'authoryourbrand.firebaseapp.com',
    storageBucket: 'authoryourbrand.appspot.com',
    measurementId: 'G-CV2MXRPQ12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_e0j7T9_yxfJJY5v8pPt3qnEboGXHz4',
    appId: '1:549681889329:android:70a70795f7eb2185e75510',
    messagingSenderId: '549681889329',
    projectId: 'authoryourbrand',
    storageBucket: 'authoryourbrand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmiLd885tT9wXHtFVCUcnUT4dMyYmp4Do',
    appId: '1:549681889329:ios:881c21c5c872b9fee75510',
    messagingSenderId: '549681889329',
    projectId: 'authoryourbrand',
    storageBucket: 'authoryourbrand.appspot.com',
    iosBundleId: 'com.example.whiteLabelCommunityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmiLd885tT9wXHtFVCUcnUT4dMyYmp4Do',
    appId: '1:549681889329:ios:881c21c5c872b9fee75510',
    messagingSenderId: '549681889329',
    projectId: 'authoryourbrand',
    storageBucket: 'authoryourbrand.appspot.com',
    iosBundleId: 'com.example.whiteLabelCommunityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCXeWfY5-l7pgIYMD7H8MBDhypYEEvxmo',
    appId: '1:549681889329:web:3317cb5ffa3bc60be75510',
    messagingSenderId: '549681889329',
    projectId: 'authoryourbrand',
    authDomain: 'authoryourbrand.firebaseapp.com',
    storageBucket: 'authoryourbrand.appspot.com',
    measurementId: 'G-KJZLV4282K',
  );

}